# Generated by Django 6.0 on 2026-01-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('risk_owner', models.CharField(choices=[('Compliance', 'Compliance'), ('Finance', 'Finance'), ('IT', 'IT'), ('Operations', 'Operations'), ('Security', 'Security')], max_length=50)),
                ('risk_category', models.CharField(choices=[('Access Control', 'Access Control'), ('Business Continuity', 'Business Continuity'), ('Configuration', 'Configuration'), ('Data Protection', 'Data Protection'), ('Third-party', 'Third-party')], max_length=50)),
                ('likelihood', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('impact', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('risk_score', models.IntegerField(editable=False)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Mitigated', 'Mitigated'), ('Closed', 'Closed'), ('Accepted', 'Accepted')], default='Open', max_length=20)),
                ('control_effectiveness', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('last_updated', models.DateField(auto_now=True)),
                ('is_mitigated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Risk',
                'verbose_name_plural': 'Risks',
                'ordering': ['-risk_score', '-last_updated'],
            },
        ),
    ]
